programas_de_tv_semi_restful/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tv_shows.urls")),
    path('admin/', admin.site.urls),
]

tv_shows/urls.py
from django.urls import path
from . import views

app_name = "tv_shows"
urlpatterns = [
    path("", views.root, name="root"),
    path("shows", views.home, name="home"),
    path("shows/new", views.new_show, name="new_show"),
    path("shows/create", views.create_show, name="create_show"),
    path("shows/<show_id>", views.show, name="show"),
    path("shows/<show_id>/edit", views.edit_show, name="edit_show"),
    path("shows/<show_id>/update", views.update_show, name="update_show"),
    path("shows/<show_id>/delete", views.delete_show, name="delete_show"),
    path("networks", views.networks, name="networks"),
    path("networks/new", views.new_network, name="new_network"),
    path("networks/<network_id>", views.network, name="network"),
    path("networks/<network_id>/edit", views.edit_network, name="edit_network"),
    path("networks/<network_id>/delete", views.delete_network, name="delete_network")
]

tv_shows/models.py
from __future__ import unicode_literals
from django.db import models
import datetime

# Create your models here.
class ShowManager(models.Manager):
    def basic_validator(self, postData):
        #creo un diccionario con los errores key/value
        errors = {}
        #valido que el campo "title" tenga al menos 2 caracteres y saco los espacios con strip
        if len(postData["title"].strip()) < 2:
            errors["title"] = "Title must be at least 2 characters"
        #valido que el campo "networks" exista
        if not postData["networks"].isdigit():
            errors["networks"] = "Please select a network"
        #valido que el campo "release_date" exista
        if len(postData["release_date"]) < 1:
            errors["release_date"] = "Please enter release date"
        #valido que el campo "release_date" sea mayor a la fecha actual
        if postData["release_date"] > str(datetime.date.today()):
            errors["release_date"] = "Release date is in the future...."
        #valido que el campo "description" tenga al menos 10 caracteres y saco los espacios con strip
        if len(postData["description"].strip()) > 0 and len(postData["description"].strip()) < 10:
            errors["description"] = "Description must be at least 10 characters (blank is OK)"
        #retorno errores
        return errors
        

class Network(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("id",)
        app_label = "tv_shows"
    
    def __str__(self):
        return self.name
    
class Show(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=500, blank=True)
    release_date = models.DateField()
    networks = models.ForeignKey(Network, related_name="shows", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ShowManager()

    class Meta:
        ordering = ("id",)
        app_label = "tv_shows"

    def __str__(self):
        return self.title

tv_shows/views.py
from django.shortcuts import redirect, render, HttpResponse, get_object_or_404
from .models import *
from django.contrib import messages

# Create your views here.
def root(request):
    return redirect("/shows")

def home(request):
    context = {
        "show" : Show.objects.all(),
    }
    return render(request, "tv_shows/shows.html", context)

def new_show(request):
    context = {
        "networks" : Network.objects.all()
    }
    return render(request, "tv_shows/new.html", context)

def create_show(request):
    if request.method == "GET":
        return redirect("/shows/new")
    elif request.method == "POST":
        # pasar los datos al método que escribimos y guardar la respuesta en una variable llamada errores
        errors = Show.objects.basic_validator(request.POST)
        # compruebe si el diccionario de errores tiene algo en él
        if len(errors) > 0:
            # si el diccionario de errores contiene algo, recorra cada par clave-valor y cree un mensaje flash
            for key, value in errors.items():
                messages.error(request, value)
            # imprimo en la consola para revisar los datos
            #print(request.POST["release_date"])
            #print(str(datetime.date.today()))
            # redirigir al usuario al formulario para corregir los errores
            return redirect("/shows/new")
        else:
            title = request.POST["title"]
            description = request.POST["description"]
            networks = request.POST["networks"]
            release_date = request.POST["release_date"]
            obj = Show.objects.create(title=title, networks_id=networks, release_date=release_date, description=description)
            obj.save()
            messages.success(request, "Show created successfully!!!")
            return redirect(f"/shows/{obj.id}")

def edit_show(request, show_id):
    context = {
        "show" : Show.objects.get(id=show_id),
        "networks" : Network.objects.all().exclude(shows__id=show_id)
    }
    return render(request, "tv_shows/edit.html", context)

def update_show(request, show_id):
    if request.method == "GET":
        return redirect("/shows")
    elif request.method == "POST":
        show = Show.objects.get(id=show_id)
        errors = Show.objects.basic_validator(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value)
            return redirect(f"/shows/{show.id}")
        else:
            new_network_id = request.POST['networks']
            new_network = Network.objects.get(id=new_network_id)

            show.title = request.POST["title"]
            show.description = request.POST["description"]
            show.networks = new_network
            show.release_date = request.POST["release_date"]
            show.save()
            print(show.networks.id)
            print(request.POST["networks"])
            messages.success(request, "Show updated successfully!!!")

            return redirect(f"/shows/{show.id}")


def delete_show(request, show_id):
    Show.objects.get(id=show_id).delete()
    return redirect("/")

def show(request, show_id):
    context = {
        #"show" : Show.objects.get(id=show_id)
        "show" : get_object_or_404(Show, id=show_id)
    }
    return render(request, "tv_shows/show.html", context)

###Networks###

def networks(request):
    context = {
        "network" : Network.objects.all()
    }
    return render(request, "tv_shows/networks.html", context)

def new_network(request):
    return HttpResponse(f"placeholder for new network form")

def create_network(request):
    pass

def edit_network(request, network_id):
    return HttpResponse(f"edit network id={network_id}")

def update_network(request, show_id):
    return HttpResponse(f"update network id={show_id}")

def delete_network(request, network_id):
    return HttpResponse(f"delete network id={network_id}")

def network(request, network_id):
    context = {
        "network" : get_object_or_404(Network, id=network_id)
    }
    return render(request, "tv_shows/network.html", context)

tv_shows/templates/tv_shows/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Template Django + Bootstrap">
    <meta name="author" content="Mauricio Abarca">
    <meta name="keywords" content="actividad, curso, ejercicio, html, css, bootstrap, Django">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <!-- Mi CSS-->
    <link rel="stylesheet" href="{% static 'tv_shows/assets/css/styles.css' %}">
    <!-- Mis JS-->
    <script src="{% static 'tv_shows/assets/js/scripts.js' %}"></script>
</head>
<body>
    <div class="wrapper">
        {% include "tv_shows/navbar.html" %}
        <div class="container-fluid p-3 bg-light">
            <div class="container">
                <div class="row">
                    <h3>{% block header %}{% endblock %}</h3>
                </div>
                <hr>
                <div class="row justify-content-center">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

tv_shows/templates/tv_shows/edit.html
{% extends "tv_shows/base.html" %}
{% block title %}Edit Tv Show {{ show.id }}{% endblock %}
{% block header %}Edit Tv Show {{ show.id }}{% endblock %}
{% block content %}
<div class="col-6">
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'tv_shows:update_show' show.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="mb-3">
                <label for="title" class="form-label fw-bold">Title:</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ show.title }}">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <label for="networks" class="form-label fw-bold">Network:</label>
                <select class="form-select" name="networks" id="networks">
                    <option value="{{ show.networks.id }}" selected="selected">{{ show.networks.name }}</option>
                    {% for network in networks %}
                    <option value="{{ network.id }}">{{ network.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <label for="release_date" class="form-label fw-bold">Release date:</label>
                <input type="date" class="form-control" name="release_date" id="release_date" value="{{ show.release_date|date:'Y-m-d' }}">
            </div>
        </div>
        <div class="row">
            <div class="mb-3">
                <label for="description" class="form-label fw-bold">Description:</label>
                <textarea class="form-control" name="description" id="description" rows="3">{{ show.description }}</textarea>
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-danger btn-sm">Save</button>
            <a class="btn btn-success btn-sm" href="{% url 'tv_shows:show' show.id %}" role="button">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

tv_shows/templates/tv_shows/modals.html
<!-- modal para delete -->
<div class="modal fade" id="delete_modal" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Show</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <h6 class="modal-text">Are you sure you want to delete the this show?</h6>
                <h5 class="modal-text text-danger" >This process cannot be undone.</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
                <a href="#" id="confirmar-borrar" class="btn btn-danger">Si</a>
            </div>
        </div>
    </div>
</div>

tv_shows/templates/tv_shows/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-lg-0">
                <li class="nav-item"><a class="nav-link"  href="{% url 'tv_shows:networks' %}">Networks</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tv_shows:home' %}">Tv Shows</a></li>
            </ul>
        </div>
    </div>
</nav>

tv_shows/templates/tv_shows/networks.html
{% extends "tv_shows/base.html" %}
{% block title %}Read (All){% endblock %}
{% block header %}Networks{% endblock %}
{% block content %}
<div class="row">
    <div class="table-responsive">
        <table class="table table-bordered border-dark table-striped table-hover">
            <thead>
                <tr class="table-dark">
                    <th class="text-center">ID</th>
                    <th>Network</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for i in network %}
                <tr>
                    <td class="text-center"><a href="{% url 'tv_shows:network' i.id %}">{{ i.id }}</a></td>
                    <td>{{ i.name }}</td>
                    <td class="text-center">
                        <a class="me-2" href="{% url 'tv_shows:network' i.id %}"><i class="far fa-eye"></i></a> |
                        <a class="me-2" href="{% url 'tv_shows:edit_network' i.id %}"><i class="fas fa-pencil-alt"></i></a> |
                        <a href="{% url 'tv_shows:delete_network' i.id %}"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-secondary btn-sm" href="{% url 'tv_shows:new_network' %}" role="button">Add a New Network</a>
    </div>
</div>
{% endblock %}

tv_shows/templates/tv_shows/new.html
{% extends "tv_shows/base.html" %}
{% block title %}Create{% endblock %}
{% block header %}New Tv Show{% endblock %}
{% block content %}
<div class="col-5">
    {% if messages %}
    <ul class="text-danger">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="{% url 'tv_shows:create_show' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="mb-3">
                <label for="title" class="form-label fw-bold">Title:</label>
                <input type="text" class="form-control" name="title" id="title" placeholder="Title">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <label for="networks" class="form-label fw-bold">Network:</label>
                <select class="form-select" name="networks" id="networks">
                    <option selected>Select Network</option>
                    {% for network in networks %}
                    <option value="{{ network.id }}">{{ network.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <label for="release_date" class="form-label fw-bold">Release date:</label>
                <input type="date" class="form-control" name="release_date" id="release_date" placeholder="release_date">
            </div>
        </div>
        <div class="row">
            <div class="mb-3">
                <label for="description" class="form-label fw-bold">Description:</label>
                <textarea class="form-control" name="description" id="description" rows="3"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-secondary btn-sm">Add</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

tv_shows/templates/tv_shows/show.html
{% extends "tv_shows/base.html" %}
{% load static %}
{% block title %}Read (One){% endblock %}
{% block header %}Tv Show {{ show.id }}{% endblock %}
{% block content %}
<div class="row">
    {% if messages %}
    <ul class="text-success list-unstyled">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="col-9">
        <h4><span class="fw-bold">Title: </span>{{ show.title }}</h4>
        {% if show.description %}
        <p><span class="fw-bold">Description: </span>{{ show.description }}</p>
        {% endif %}
        <p><span class="fw-bold">Network: </span>{{ show.networks }}</p>
        <p><span class="fw-bold">Release date: </span>{{ show.release_date|date:"F d, Y" }}</p>
    </div>
    <div class="col-3">
        <img class="show_img img-thumbnail" src="{% static 'tv_shows/assets/img/show/1200px-No-Image-Placeholder.svg.png' %}" alt="placeholder for show image">
    </div>
</div>
<div class="row mt-5">
    <p><span class="fw-bold">Last Updated: </span>{{ show.updated_at|date:"F d, Y h:i a" }}</p>
</div>
<div>
    <a class="btn btn-secondary btn-sm" href="{% url 'tv_shows:edit_show' show.id %}" role="button">Edit</a>
    <a class="btn btn-danger btn-sm modal-borrar" data-bs-toggle="modal" data-bs-target="#delete_modal" href="{% url 'tv_shows:delete_show' show.id %}" data-href="{% url 'tv_shows:delete_show' show.id %}" role="button">Delete</a>
    <a class="btn btn-success btn-sm" href="{% url 'tv_shows:home' %}" role="button">Go back</a>
</div>
{% include "tv_shows/modals.html" %}
{% endblock %}

tv_shows/templates/tv_shows/shows.html
{% extends "tv_shows/base.html" %}
{% block title %}Read (All){% endblock %}
{% block header %}Tv Shows{% endblock %}
{% block content %}
<div class="row">
    <div class="table-responsive">
        <table class="table table-bordered border-dark table-striped table-hover">
            <thead>
                <tr class="table-dark">
                    <th class="text-center">ID</th>
                    <th>Title</th>
                    <th>Network</th>
                    <th>Release Date</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in show %}
                <tr>
                    <td class="text-center"><a href="{% url 'tv_shows:show' i.id %}">{{ i.id }}</a></td>
                    <td>{{ i.title }}</td>
                    <td>{{ i.networks }}</td>
                    <td>{{ i.release_date|date:"F d, Y" }}</td>
                    <td class="text-center">
                        <a class="me-2" href="{% url 'tv_shows:show' i.id %}"><i class="far fa-eye"></i></a>
                        <a class="me-2" href="{% url 'tv_shows:edit_show' i.id %}"><i class="fas fa-pencil-alt"></i></a>
                        <a class="text-decoration-none modal-borrar" data-bs-toggle="modal" data-bs-target="#delete_modal" href="{% url 'tv_shows:delete_show' i.id %}" data-href="{% url 'tv_shows:delete_show' i.id %}"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-secondary btn-sm" href="{% url 'tv_shows:new_show' %}" role="button">Add a New Show</a>
    </div>
</div>
{% include "tv_shows/modals.html" %}
{% endblock %}